config_files = ["config_exp.toml", "config_exp_observations.toml", "config_exp_surfex.toml",
                "config_exp_eps.toml"]

["config_exp.toml"]
blocks = ["general", "compile", "domain", "initial_conditions", "forecast", "forcing"]

["config_exp_observations.toml"]
blocks = ["observations"]

["config_exp_surfex.toml"]
blocks = ["SURFEX"]

["config_exp_eps.toml"]
blocks = ["eps"]
